### ISSUE TITLE
MySQL SQL_CACHE

### ISSUE THREAD

**Issue by aliaspooryorik** [coldbox-modules/qb#11]
Feature request :)

Been looking into qb and really like it. At the moment we heavily use `SQL_CACHE` with MySQL selects. Was wondering if you'd consider adding that?

**Comment by elpete** [comment]
This should be possible right now using `raw`.

```
var builder = new qb.models.Query.Builder(
    new qb.models.Query.Grammars.MySQLGrammar(),
    new qb.models.Query.QueryUtils()
);
var sql = builder
   .from( "users" )
   .select( builder.raw( "SQL_CACHE id" ) )
   .toSQL();

// SELECT SQL_CACHE id FROM `users`
```

However, I'm open to a helper method or something like that.  To start, I think `selectRaw` would be a nice addition.  That would simplify the above example to this:

```
var builder = new qb.models.Query.Builder(
    new qb.models.Query.Grammars.MySQLGrammar(),
    new qb.models.Query.QueryUtils()
);
var sql = builder
   .from( "users" )
   .selectRaw( "SQL_CACHE id" )
   .toSQL();

// SELECT SQL_CACHE id FROM `users`
```

Do you have any other ideas for this?

**Comment by aliaspooryorik** [comment]
Happy to go with the currently supported way, didn't know you could do that 👍 

Think `selectRaw` could be quite handy for situations where you want to put say a case statement  or coalsce into the select.

**Comment by elpete** [comment]
Sounds good.  I've opened up a ticket for that: #12
