### ISSUE TITLE
qb breaks code when there is a space behind a table alias 

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/qb#122]
Example .from("myTable as alias ") will break, while .from("myTable as alias") is OK

I had a quick look at 7.10 and I assume the basegrammar has changed for alias handling. I think it would be smart to trim the table input so you don’t have regexmatching for spaces on the beginning and end of the table string. There should be no spaces anyway, but SQL is a bit more forgiving than qb.

**Comment by stoneflystudios** [comment]
Please ignore, this issue already resolved in branch `next`.
