### ISSUE TITLE
SqlServerGrammar uses DECIMAL for FLOAT

### ISSUE THREAD

**Issue by DiscountDarcy** [coldbox-modules/qb#125]
`typeFloat()` produces a DECIMAL datataype for MSSQL instead of a Float type.

Propose that this is changed so that typeFloat produces a float and typeDecimal produces a decimal, e.g.

```
    function typeDecimal( column ) {
        return "DECIMAL(#column.getLength()#,#column.getPrecision()#)";
    }

function typeFloat( column ) {
	if ( column.getPrecision() != 0 ) {
		return "FLOAT(#column.getPrecision()#)";
	}

	return "FLOAT";
}
```

Differences: https://stackoverflow.com/questions/1056323/difference-between-numeric-float-and-decimal-in-sql-server#:~:text=Float%20is%20Approximate%2Dnumber%20data,use%20decimal%20for%20money%20saving.

**Comment by elpete** [comment]
Sure thing!
