### ISSUE TITLE
incorrect Date detection in InferSqlType()

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/qb#128]
Today datatype autodection in qb fooled me again.
Look at this and you see what I mean
`writedump(IsDate( "06 12345678" ))` will return true. But this is not a date, but a (Dutch) cell phone number.
I had problems updating contactinfo for some customers. InferSqlType() is detecting my phone number string as a date. I remember it also detected strings with numbers incorrectly in the past, but this has been fixed long ago with checkIsActuallyNumeric . I was wondering if we could do a simular trick for dates? Now I solved it by explicitly setting a datatype varchar. But I would rather set my date fields explicitly instead of an unreliable datatype for a simple string.

**Comment by elpete** [comment]
Closed by https://github.com/coldbox-modules/qb/pull/130
