### ISSUE TITLE
MSSQL: Paginate MaxRows 0 Returns Error "FETCH clause must be greater then zero"

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/qb#143]
On MSSQL Server if you pass along a `maxRows` value of 0 and then `paginate()` you will get the following error:
`The number of rows provided for a FETCH clause must be greater then zero`
[MSSQL rule reference with offset/fetch](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15)

Here's a sample qb statement to reproduce the issue:
```
qb.from( "user" ).forPage( 1, 0 ).paginate();
```

This is the SQL it generates
`SELECT * FROM [user] OFFSET 0 ROWS FETCH NEXT 0 ROWS ONLY`

I was actually surprised to learn that using a `maxRows` value of 0 attempts to return 0 results instead of all of the results. 
  I interpret the meaning of `maxRows:0` to be: "_Query records from the table with no maxrows_". In other words, "_don't limit the results_".
  
If someone does not want to retrieve any results whatsoever, they should simply do a `count()`.  It doesn't make sense to return a pagination object with no page data unless the `totalPages` value is also 0.  Does that make sense?

```
{
    "pagination": {
        "maxRows": 0,
        "offset": 0,
        "page": 1, // if I don't have data, this isn't really page 1
        "totalPages": ?,  // you can't have total pages without maxRows!
        "totalRecords": 45  // a simple count() feels more appropriate if the user only wants this information
    },
    "results": [ ]
}
```

Also, from a UI consideration, oftentimes we give users the freedom to display X number of results in a recordset. Giving them the option to display all results can be very handy in some situations.  If QB treated `maxRows = 0` as returning all results, it would solve the above problem and also create greater flexibility for the tool.

This is what I would expect from setting `maxRows` to 0:

```
{
    "pagination": {
        "maxRows": 0,
        "offset": 0,
        "page": 1,
        "totalPages": 1, 
        "totalRecords": 1000  // or whatever the record total is
    },
    "results": [ ... ] // all records
}
```

Just my two cents. Hopefully, the above information is helpful.

**Comment by elpete** [comment]
First, let's address your use case in current qb:
```cfc
param rc.page = 1;
param rc.maxRows = 10;
qb.from( "user" )
    .when(
        rc.maxRows > 0,
        ( qb ) => qb.forPage( rc.page, rc.maxRows )
    )
    .get();
```

This would let you retrieve all the results when the `maxRows` was 0 or even negative.

On to your other points.

>  I interpret the meaning of maxRows:0 to be: "Query records from the table with no maxrows". In other words, "don't limit the results".

I can see this interpretation.  I wrote this with the intepretation that `0` maxRows meant bring back no results.  I agree it doesn't make much sense to do that from a user's perspective, but bringing back all results can have major performance implications.

> It doesn't make sense to return a pagination object with no page data unless the totalPages value is also 0.

Actually, there are many use cases where you bring back no records on page 1.  For instance, if you are filtering the dataset and the combination of filters returns no records you would have 1 `page` of 0 records with a `totalPages` of 1.  There is always one page in pagination, even if it is empty.

I am very hesitant to add the behavior to bring back all records to `paginate`.  The safety I get from `paginate` is that I will never try to load all the hundreds, thousands, or even millions of records in a table.  If you, as the developer, want to expose that you can, as I showed above.  It might not be as succinct, but I think it's worth the trade-off to keep the security of `paginate`.

One last side note, in most cases I would recommend clamping your `maxRows` variable, especially if you accept it from the user.  This looks something like this:

```cfc
private numeric function clamp( lowerLimit, result, upperLimit ) {
    arguments.result = ceiling( arguments.result );
    arguments.result = min( arguments.result, arguments.upperLimit );
    return max( arguments.lowerLimit, arguments.result );
}
```

```cfc
param rc.page = 1;
param rc.maxRows = 10;
qb.from( "user" )
    .paginate( rc.page, clamp( 1, rc.maxRows, 100 ) );
```

With this you will guarantee not to have a user bring down your server by trying to select 1,000,000 rows in one page.  This of course depends on your particular use case.

I hope this helps you understand why I don't plan to add this behavior.  If you still feel like this should be in the core, I would recommend either creating a custom `QueryBuilder` class that extends qb's and overriding the `forPage` method in it or forking this repository and making your changes there.

Thanks for contributing!

**Comment by homestar9** [comment]
I like that clamp function! That's a good tip. Thanks @elpete
