### ISSUE TITLE
MAX does not work for dates

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#146]
The following code returns 0.  I can't get to the final SQL, but it should look like the SQL below the qb code.  The final block is what I fell back to.

```
qb.newQuery()
              .from('ref_v2.ref_calendar_dates')
              .where('day_of_week','<',6)
              .andWhereRaw('ref_date < cast(getDate() as date)')
              .andWhereNotIn('ref_date', function(q){
                q.from('ref_v2.ref_calendar_holidays')
                  .select('holiday_date')
                  .where('fref_exchange_code','NYS')
                  .andWhereRaw('year(holiday_date) in (YEAR(getDate()),YEAR(getDate())-1)')
              })
              .max(column='ref_date',options={datasource:'factset'})
```
```
SELECT max(ref_date)
FROM [ref_v2].[ref_calendar_dates] 
WHERE [day_of_week] < 6 
	AND ref_date < cast(getDate() as date) 
	AND [ref_date] NOT IN (SELECT [holiday_date] FROM [ref_v2].[ref_calendar_holidays] WHERE [fref_exchange_code] = 'NYS' AND year(holiday_date) in (YEAR(getDate()),YEAR(getDate())-1))
```
```
qb.newQuery()
              .from('ref_v2.ref_calendar_dates')
              .where('day_of_week','<',"6")
              .andWhereRaw('ref_date < cast(getDate() as date)')
              .andWhereNotIn('ref_date', function(q){
                q.from('ref_v2.ref_calendar_holidays')
                  .select('holiday_date')
                  .where('fref_exchange_code','NYS')
                  .andWhereRaw('year(holiday_date) in (YEAR(getDate()),YEAR(getDate())-1)')
              })
              .orderBy("ref_date","desc")
              .value(column='ref_date',options={datasource:'factset'})
```

**Comment by elpete** [comment]
Could you please show me the SQL code that is generated?

**Comment by Daemach** [comment]
I'm not sure how to get the final output as the max clause changes things.  I usually use toSQL()

**Comment by elpete** [comment]
You can:
1. Add a log listener for `qb.models.Grammars` or set your root looger to `DEBUG`.
2. Install cbdebugger and turn on the qb/Quick view.
3. Add a ColdBox Interceptor listening to `postQBExecute`.
4. Put a `writeDump` in the source in `BaseGrammar#runQuery`.

**Comment by Daemach** [comment]
SELECT MAX([ref_date]) AS "aggregate" 
FROM [ref_v2].[ref_calendar_dates] 
WHERE [day_of_week] < 6 AND ref_date < cast(getDate() as date) AND [ref_date] NOT IN (SELECT [holiday_date] FROM [ref_v2].[ref_calendar_holidays] WHERE [fref_exchange_code] = 'NYS' AND year(holiday_date) in (YEAR(getDate()),YEAR(getDate())-1))

**Comment by elpete** [comment]
Those look basically identical (with the exception of the `AS "aggregate"` alias.

What error are you getting?

**Comment by Daemach** [comment]
It returns a number (0) as the result, rather than a date.  

After testing further, I have a hunch it's a casting issue within qb.  When I run the SQL I just sent with queryexecute, or from SSMS, I get a date back.

**Comment by elpete** [comment]
Huh...you're right.  I'm not sure why this code exists, but it does: https://github.com/coldbox-modules/qb/blob/bac94a59a95e4207cb4ca9bd6fc7cdaae806320f/models/Query/QueryBuilder.cfc#L3099

That seems wrong and maybe not needed.  I'll look in to it.  Thanks for helping me debug this.

**Comment by Daemach** [comment]
Yeah - good catch. Odd problem. Thanks for working on it!

**Comment by elpete** [comment]
Reopening since the issue still exists.
