### ISSUE TITLE
Please add .insert([fieldnames],function(q){}) to generate "insert into tablename select from" SQL

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#148]
I build temp tables to handle large datasets, then usually do "insert into tablename select distinct * from"  or "insert into tablename ([fieldnames]) select distinct [fieldnames] from ... where..."  It's a shame to have to drop back to queryExecute for these.

I'm not sure what the best combination of argument to add would be.  Perhaps it would be better to do .insert(function([fieldnames] | '*",q){}) so you could use isClosure() on the first argument.

**Comment by elpete** [comment]
I think we could accomplish this with the following syntax:
```cfc
qb.table( "customers" ).insertUsing( [ "SupplierName", "City", "Country" ], function( qb ) {
    qb.from( "suppliers" ).select( [ "SupplierName", "City", "Country" ] );
} );
```
The passed in function could also be a `QueryBuilder` instance.

**Comment by Daemach** [comment]
I'm fine with any solution for this and "select into from" situations, though I just realized that selectraw might be enough for the latter.  Would be good to add to the documentation as a hint if that's the case.
