### ISSUE TITLE
compileOffset and compileLimitValue do not parameterize values

### ISSUE THREAD

**Issue by dariusj18** [coldbox-modules/qb#164]
Often pagination information comes from userland, having the offset and limit written directly into the query opens up queries to SQL injection attacks.

**Comment by elpete** [comment]
Interesting.  I wasn't aware params worked at that part of a query.  This is probably a good improvement, but there is not currently any SQL injection attack vector since the `limit`, `take`, and `offset` methods all specify `numeric` types.

**Comment by elpete** [comment]
Initial testing showed that MySQL cannot have `LIMIT` be bound, so I'm not sure if this will be too viable.  If the other database grammars support it, I can work around that, but I haven't tested that yet.

**Comment by elpete** [comment]
This doesn't seem to work in SQL Server either.  I'm not sure if this is a JDBC thing Lucee and ACF needs to support, but it's not something I can work around.  Closing this ticket for now.  Feel free to reopen if Lucee or ACF changes.
