### ISSUE TITLE
Eager loading / relationship-stitching in QB

### ISSUE THREAD

**Issue by DiscountDarcy** [coldbox-modules/qb#167]
The Problem:

When dealing with significant quantities (e.g. reporting), instantiating Quick entities is not practical due to the `createObject` cost. `.retrieveQuery()` provides a relief valve that works for entity fields and subselects, but doesn't work for related entities or eager loading.

The Solution:

Provide some mechanism in QB to attach the output of another QB expression to the result set, and then integrate it with Quick such that `.with([ "relatedObj1", "relatedObj2" ])` will stitch those results into the parent query in the event that we `.retrieveQuery()` on a Quick entity that has previously had eager-loading calls made to it.

The Approach:

This may just appear deceptively simple before I actually sit down to do it, but it seems like we just need a place on a QueryBuilder object to store any other QueryBuilder objects we want executed and then stitched into the result set. Probably the hard part is relating the results to the right parents, since QB would have to know the foreign key relationships in each object to map the related entities to the correct structs in the parent entities. 

I have a bunch of work to do that needs something like this anyway, so I can do it as a patch provided I'm on the right track.

**Comment by DiscountDarcy** [comment]
Just a note that this is actually really easy to do in MSSQL *if* you're using their native JSON support, because you can just put the 'eager load' query on a hasMany as a subselect and it will bring in the whole object for you, as described here:

https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15

I know it's preferable to have a grammar-neutral way of doing this, but the efficiency gains in MSSQL are out of this world - we use this technique to marshal > 70 megabytes of data on a single API request and it takes a few seconds (as opposed to having CF serialize it all, which takes minutes).

**Comment by elpete** [comment]
This has been added in Quick by using `asQuery`.  No current plans to port this to qb.
