### ISSUE TITLE
Convenience method:  .dump()

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#178]
I use .tap((q)=>dump(q.toSQL()))  quite a bit.  It would be great to have a .dump() method that does this.  Again, an alias just to save typing.

Even better if it could format the SQL, putting SELECT, FROM, WHERE, ORDER, GROUP, etc on their own lines, and ideally includes the actual data passed into the where clauses (and everywhere else) so I can see **exactly** what is going to be passed to the server.  This would be immensely useful for troubleshooting and testing...  I love writing QB, but it's harder to read than SQL and for really hairy blocks, like the one below, it would be much easier to troubleshoot with something like this.  It could be used in the same manner as tap, but might be more useful as an interceptor for get/first/value, etc.  If it finds dump() in the chain, it should dump the query to the browser instead of sending to the database.  and if I could pass in dump(true) to abort at that point as well, it would be WONDERFUL.

```
qb.newQuery()
      .from('MARS_IN_GEOS g')
      .join('MARS_IN_SECURITY s','g.security_id','s.security_id')
      .leftjoin('MARS_IN_BENCH_HOLDINGS bh', (j)=>{
        j.on('s.security_id','bh.security_id')
        j.where('bench_id',benchmark)
      })
      .select('g.security_id AS SecurityID, s.security_name as SecurityName, s.Ticker, s.cusip_9 AS CUSIP, s.SEDOL, bh.bench_id AS Benchmark, bh.pct_wt AS BenchmarkWeight')
      .whereNotIn('g.security_id', (q)=>{
        q.from('MARS_IN_PRICE').values('security_id')
      })
      .andWhereNotIn('country', oppressiveRegimes)
      .andWhereNotIn('g.security_id', (q)=>{
        q.from('mars_in_geos').where('country', 'HK').andWhere('SOE', 1).values('security_id')
      })
      .andWhere((q)=>{
        q.where((q1)=>{
          q1.whereIn('g.security_id',(q2)=>{
            q2.from('MARS_IN_BENCH_HOLDINGS').whereIn("bench_id", 'Mstar_Dev_xNA_TME').values('security_id')
          })
          .orWhereIn('s.custom_10',(q3)=>{
            q3.from('MARS_IN_BENCH_HOLDINGS bh')
              .join('MARS_IN_SECURITY s1', 'bh.security_id', 's1.security_id')
              .whereIn('bench_id', 'Mstar_Dev_xNA_TME')
              .values('s1.custom_10')
          })
        })
        .orWhere('dmem','EM')
      })
      .get()
```

**Comment by elpete** [comment]
Already there.

Docs: https://qb.ortusbooks.com/query-builder/debugging#dump
CFCasts: https://cfcasts.com/series/whats-new-in-qb-8/videos/what's-new-in-qb-8-dump-helper

**Comment by Daemach** [comment]
Thanks for your patience and foresight ;)  Clearly I need to keep up with
the release notes...

Any chance you could insert breaks to make it more readable?  My queries
aren't trivial and I end up having to copy/paste and manually insert breaks
on the verbs.

**Comment by elpete** [comment]
That's not quite an easy task.  I haven't found any good Java library to do
it, neither am I sure I want to include a library to do it.  I'm open to
suggestions, but I don't really want to parse SQL myself to format it
nicely.

**Comment by Daemach** [comment]
I wonder if one of these could work - this one uses a hibernate library:
https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/jdbc/util/BasicFormatterImpl.html

https://github.com/vertical-blank/sql-formatter

**Comment by Daemach** [comment]
The second one includes dialects, which may be useful...
