### ISSUE TITLE
valuesRaw or use selectRaw statement?

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#183]
I find myself wanting to get just an array of values quite a bit, but 50% of the time what I need isn't in a column name, but rather a generated value such as the query below.  How difficult would it be to add support (in any fashion) for something like the following?  

```
    var unAssigned = qb.from('scalerJobs')
                        .where('scalerServerID',0)
                        .selectRaw('(benchmarkNames + buylistNames) * .153 as predicted')
                        .values(column='predicted', options={ datasource:server.scaler.vAdminDB })
```

**Comment by elpete** [comment]
Interesting.

One option you have right now is to put that computed column in the database.  `SchemaBuilder` can generate [virtual](https://qb.ortusbooks.com/schema-builder/column-modifiers#virtualas) and [computed](https://qb.ortusbooks.com/schema-builder/column-modifiers#storedas) columns.

```cfc
t.float( "predicted" ).storedAs( "(benchmarkNames + buylistNames) * .153" );
```

One other workaround (that you might even be using right now is to execute the query and map over the results into the values:

```cfc
qb.from( "scalerJobs" )
    .where( "scalerServerID", 0 )
    .selectRaw( "(benchmarkNames + buylistNames) * .153 as predicted" )
    .get( options = { "datasource": server.scaler.vAdminDB } )
    .map( ( row ) => row.predicted );
```

Another option we should definitely support is passing `Expression`s to `value` and `values` (think `qb.raw()`).  That's not currently possible, but I'd want that to be.  That would make your example look like the following:

```cfc
qb.from( "scalerJobs" )
    .where( "scalerServerID", 0 )
    .values(
        column = qb.raw( "(benchmarkNames + buylistNames) * .153 as predicted" ),
        options = { "datasource": server.scaler.vAdminDB }
    );
```

Then we could also add `valueRaw` and `valuesRaw` helper methods to avoid having to call `raw` manually.

**Comment by Daemach** [comment]
Sounds great.  I am using the map method currently but looking forward to something more elegant.  Thanks!
