### ISSUE TITLE
No null support in queryUtils isfloatingpoint

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/qb#192]
I have a null value in an object
property name="rack_id" type="string";
this is usually a guid, or NULL
this shows up in isFloatingPoint in queryutils with the following binding
cfsqlType=CF_SQL_NUMERIC
list= false
null = true
value = null
This returns an error with these values, because you can’t do a tostring() on a null. Code shouldn’t arrive there anyway. If null = true in the binding I think it should return false directly.

checkIsActuallyNumeric makes a null value numeric, is that correct?

**Comment by wpdebruin** [comment]
there are more issues with qb. I can’t insert a struct with null values in a database, because it is failing on the isFloatingPoint in the extractBinding method in qb.  Root cause here is that a null value is incorrectly detected as numeric, and there are more datadetection methods which return true if you feed them a null value. Not sure if that was intended this way

**Comment by wpdebruin** [comment]
infersqltype(null) returns CF_SQL_NUMERIC. A null value is NOT numeric
the private function checkIsActuallyNumeric(null) returns true. should be false
private checkIsActuallyDate returns true, should be false
private function isFloatingPoint errors. If you feed it a binding with a null value, it can’t handle arguments.binding.value.toString() if value is null
calculateNumberOfDecimalDigits is failing for the same reason.

**Comment by elpete** [comment]
I've reviewed what you have here and the only "missing" piece was in `inferSqlType` which was incorrectly handling nulls.

The other methods should never be reachable because the first line in `extractBinding` checks for a null value and returns early.

My guess here is the issue is actually in Quick, not qb.  Please create a test case over in Quick showing the error so we can get it fixed there.

I will still commit my fixes for the `inferSqlType` here in qb.

**Comment by wpdebruin** [comment]
I have to see your fix for inferSQLtype, but I still think it is not solved, no matter what you code there.
Let's assume you return some NONE numeric type there. There is no null type for this so I guess you are returning sqltype = varchar. But it doesn't matter, just follow the flow here.
I insert this in a database
qb.from("mytable").insert({
    rack_fk: { value: null, null: true }
   })
   
as soon as you try to insert this it hits the extractBinding function.
 But it doesnt return on the first line!! (the isnull check) because the binding is a STRUCT { value: null, null: true }, so extractbinding continues and find it is a struct.
Now it gets to structappend binding and it will ALWAYS fail on the next isFloatingPoint because that will always try to a arguments.binding.value.toString which is impossible with null values.
So you are right the checkIsActualDate and checkIsActuallyNumeric will not be hit, but the code will still fail.

**Comment by wpdebruin** [comment]
About the quick problem: it is related to both quick AND qb. I described it in the quick issue
https://github.com/coldbox-modules/quick/issues/154
It is easy to fix by changing code in quick AND qb

**Comment by elpete** [comment]
I see. I will add a test with a full struct binding passed. Thank you.

**Comment by wpdebruin** [comment]
Ok thanks. I think it is fixed now, so this issue can be closed
