### ISSUE TITLE
whereBetween doesn't like odbc timestamps, and fusionreactor doesn't like date strings...

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#199]
Fusionreactor is useful for seeing exactly what the database is seeing, and I often copy/paste the queries out of the jdbc history and into ssms to troubleshoot.  The problem is that they don't surround date strings with quotes, so I have to manually add those.  I recently found out that it handles odbc dates fine.  Wherebetween doesn't like this.  The code below yields the following .dump()

```
var pfBase = qb.from('veritiadmin.dbo.accounts_portfolioHistory h')
      .join('veritiadmin.apx.vSecurity s', (j)=>{
        j.on('h.securityID', 's.securityID')
        j.where('reportDate', createODBCDate(enddate))
      })
      .join('factset.fp_v2.fp_basic_dividends d', 's.fsym_id', 'd.fsym_id')
      .where('accountID', accountID)
      .andWhereBetween('p_divs_exdate', createODBCDate(dateAdd('yyyy', -1, endDate)), createODBCDate(enddate))
      .distinct()
      .selectRaw("d.fsym_id, p_divs_pd, currency, CASE d.currency WHEN 'USD' THEN factset.fp_v2.fp_splitadjprice(d.fsym_id, #createODBCDate(enddate)#) ELSE factset.fp_v2.fp_splitadjprice(d.fsym_id, #createODBCDate(enddate)#) * (select exch_rate_usd from factset.ref_v2.fx_rates_usd where iso_currency = d.currency and date = #createODBCDate(enddate)#) END AS price, h.percentAssets/100 as pct_wt, factset.fp_v2.fp_splitfactor_div(d.fsym_id, d.p_divs_exdate) as splitfactor")
      .dump( label = "bmBase", showBindings = true, abort = true )
```
`SELECT DISTINCT d.fsym_id, p_divs_pd, currency, CASE d.currency WHEN 'USD' THEN factset.fp_v2.fp_splitadjprice(d.fsym_id, {d '2021-09-30'}) ELSE factset.fp_v2.fp_splitadjprice(d.fsym_id, {d '2021-09-30'}) * (select exch_rate_usd from factset.ref_v2.fx_rates_usd where iso_currency = d.currency and date = {d '2021-09-30'}) END AS price, h.percentAssets/100 as pct_wt, factset.fp_v2.fp_splitfactor_div(d.fsym_id, d.p_divs_exdate) as splitfactor FROM [veritiadmin].[dbo].[accounts_portfolioHistory] AS [h] INNER JOIN [veritiadmin].[apx].[vSecurity] AS [s] ON [h].[securityID] = [s].[securityID] AND [reportDate] = {"value":"September, 30 2021 00:00:00 -0400","cfsqltype":"CF_SQL_VARCHAR","null":false} INNER JOIN [factset].[fp_v2].[fp_basic_dividends] AS [d] ON [s].[fsym_id] = [d].[fsym_id] WHERE [accountID] = {"value":"104","cfsqltype":"CF_SQL_VARCHAR","null":false} AND [p_divs_exdate] BETWEEN {"value":"September, 30 2020 00:00:00 -0400","cfsqltype":"CF_SQL_VARCHAR","null":false} AND {"value":"September, 30 2021 00:00:00 -0400","cfsqltype":"CF_SQL_VARCHAR","null":false}`

**Comment by Daemach** [comment]
I hoped this would fix it, but no luck.

```
private boolean function checkIsActuallyDate( any value ) {
        if ( isNull( arguments.value ) ) {
            return false;
        }

        if (arguments.value contains "{d '" || arguments.value contains "{ts '" ||  arguments.value contains "{t '"){
            return true;  
        } else if ( variables.strictDateDetection ) {
            return isDate( arguments.value ) && arrayContainsNoCase(
                [ "OleDateTime", "DateTimeImpl" ],
                listLast( getMetadata( arguments.value ), "." )
            );
        } else {
            return isDate( arguments.value );
        }
    }
```

**Comment by Daemach** [comment]
This may have uncovered a more significant problem...  I am passing dates (yyyy-mm-dd) to all of these functions, and they are being compared to date (not datetime) fields in SQLS.   Currently, I am running reports for the end of Q3, so var endDate = '2021-09-30'

When I use j.where('reportDate', enddate), I see the following in FR:  
![image](https://user-images.githubusercontent.com/12553953/138450972-a57beac7-157c-4b06-b220-4f147fd285ca.png)


When I use j.whereRaw('reportDate = #createODBCDate(enddate)#'), I see the following in FR: 
![image](https://user-images.githubusercontent.com/12553953/138450953-5a92b59d-26c2-447a-aa99-596e2c76f0ee.png)


This is scary because the results, in this case, **changed the output by a factor of 10**...  This may be an issue with Lucee date handling, but the end result is that I can't pass an ODBC timestamp to QB to get around it.   I would hate to have to use whereRaw everywhere now :/

This only affects QB for me - where I have to use queryExecute, such as calling sprocs, I pass in dateFormat('yyyy-mm-dd') as below, so SQLS just gets a 'yyyy-mm-dd' string:

```
queryExecute("
                        set nocount on
                        --select * From [AdvApp].[vUserSession] where licensepoolid = 1
                        
                        DECLARE @FromDate AS DATETIME
                        DECLARE @EndDate AS DATETIME
                        DECLARE @Entity AS VARCHAR(25)
                        DECLARE @SessionGUID as nvarchar(60)
                        DECLARE @ReportData VARBINARY(MAX)

                        set @SessionGUID = :sessionGUID

                        EXEC APXUser.pSessionInfoSetGuid @sessionGUID

                        EXEC APXUser.pPerformance
                        @ReportData=@ReportData OUT
                        ,@Portfolios = :portfolioCode
                        ,@FromDate = :fromDate
                        ,@ToDate = :toDate
                        ,@FeeMethod = :netOrGross
                        ,@ClassificationID = -9
                        ,@AnnualizeReturns = 'o'
                        ,@AccruePerfFees = 1
                        ,@InceptionToDate = 0

                        SELECT :accountID as accountID, :bNet as bNet, ACB,AccruedInterestDate1,AccruedInterestDate2,AccruedInterestDelta,Additions,AnnualizedIRR,AnnualizedPriceIRR,CostBasis,Dividends,Fees,FromDate,Interest,IRR,ManagementFees,ManagementFeesPaidByClient,MarketValueDate1,MarketValueDate2,NonZeroMarketValueDate1,NonZeroMarketValueDate2,PortfolioFees,PortfolioFeesPaidByClient,PriceIRR,PriceRealizedGainLossOnMval,PriceUnrealizedGainLossOnMval,RealizedGainLossOnCost,RealizedGainLossOnMval,ThruDate,TotalGain,TotalIncome,TransfersIn,TransfersOut,UnrealizedGainLossOnCost,UnrealizedGainLossOnMval,Withdrawals
                        FROM [APXUser].fPerformance (@ReportData) d
                      ",{accountID: account.id, portfolioCode: account.portfolioCode, sessionGUID: sessionGUID, netOrGross: v, fromDate: dateFormat(dateAdd('d',1,period.start),'yyyy-mm-dd'), toDate: dateFormat(period.end,'yyyy-mm-dd'), bNet: (v == 1)? 1:0}, {datasource:'APX'})
```

**Comment by elpete** [comment]
In this case, you had `strictDateDetection` turned on which meant string dates were treated as `varchar`s.  Date objects (like from `createODBCDate`) are treated as `timestamp`s.  You can force them to be treated as dates by passing a query param struct and specifying `date` as the `cfsqltype`.

I will add to qb's param type inference a `date` catch for strict date detection to help with this.

**Comment by elpete** [comment]
Please see #202 for the ticket on returning `date`s instead of `timestamp`s (when appropriate)
