### ISSUE TITLE
Update with joins doesn't like aliasing

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#207]
I always alias tables when joining, but updates with joins doesn't like that.  The code below produces invalid SQL on SQL server.

```
qb.table('synaptrix_account_history h')
      .join('veritiadmin.dbo.accounts a', 'h.account_id', 'a.portfolioCode')
      .update({
        accountID: qb.raw('a.id')
      })
```

I propose that the builder that creates the update statement use listLast(getTableName(), " ") when constructing the initial update statement (`UPDATE tablename`).  This would work properly for all of the following, and still allow me to use the alias in the joins:

```
.table('synaptrix_account_history h')
.table('synaptrix_account_history as h')
.table('synaptrix_account_history')
```

**Comment by elpete** [comment]
Can you please post the SQL that this is producing?

**Comment by Daemach** [comment]
`UPDATE [mars_231].[dbo].[synaptrix_account_history] AS [h] SET [accountID] = 1.0 FROM [mars_231].[dbo].[synaptrix_account_history] AS [h] INNER JOIN [veritiadmin].[dbo].[accounts] AS [a] ON [h].[account_id] = [a].[portfolioCode] WHERE [accountID] = 1.0`

**Comment by Daemach** [comment]
The error is `Incorrect syntax near the keyword 'AS'.`
