### ISSUE TITLE
InsertUsing - please parse columns...

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#208]
InsertUsing is a great feature, but it can be more verbose and time-consuming to write than a base SQL statement with queryExecute.  Creating string arrays for column names by hand is tedious as every value needs to be quoted, and the column list is redundant in 90+% of cases as it must also be specified in the select statement that feeds it.  And one often cannot just copy/paste the select statement as the base of the array definition due to column aliases, which are numerous when dealing with vendor databases...

To continue with the theme of QB's convenience features making it more fun to use than SQL, it would be great to reverse the source and columns arguments as a breaking change before too many people start using this feature :) When insertUsing() is called, if a `columns` array exists, use that.  Otherwise perhaps, you could generate the same array using `listtoarray( getSubSelectList() ).map( (e)=>{ listLast( e, " " ) } )`.

**Comment by Daemach** [comment]
```
qb.table('accounts_shadowHoldingsHistory')
      .insertUsing(
        columns = ["lotID","accountID","originalCostDate","originalCost","price","quantity","marketValue","pctWeight","bLongTerm"],
        source = (q)=>{
          q.from('accounts_shadowHoldings')
            .selectRaw("id as lotID,accountID,originalCostDate,originalCost,price,quantity,marketValue,pctWeight,bLongTerm")
            .where('accountID', accountID)
        }
      )

vs

  qb.table('accounts_shadowHoldingsHistory')
      .insertUsing((q)=>{
          q.from('accounts_shadowHoldings')
            .selectRaw("id as lotID,accountID,originalCostDate,originalCost,price,quantity,marketValue,pctWeight,bLongTerm")
            .where('accountID', accountID)
        }
      )

```

**Comment by elpete** [comment]
columns = accept list
insertUsing -> parse alias from selectRaw, if possible; document that (use columns if you don't want)
Mention in Raw that it doesn't automatically handle lists - use `listToArray`
Raw selects should represent 1 column, if possible.
