### ISSUE TITLE
Please return all rows when maxrows = 0

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#215]
Quasar uses maxrows = 0 to signify "all" rows, datatables uses -1.  It would be great if coldbox supported `if maxrows <= 0 then return all` rather than returning an error.

We also discussed adding a couple of new config params, something along the lines of:

capMaxRowsAt: 250
maxRowsIsAllWhen: 0/-1

If both were implemented, I would expect that if I sent maxrows = 0, it would return 250 records.  If capMaxRowsAt wasn't set, then maxrows=0 would return all records.

**Comment by elpete** [comment]
The strange question to answer here is what should the `pagination` object look like in this case?

```
{
    "totalRecords": totalRecords,
    "maxRows": 0, // Should this show negative numbers if passed?
    "totalPages": 1,
    "page": 1
    "offset": 0
}
```

**Comment by elpete** [comment]
Looks like `totalPages` will be 0.
