### ISSUE TITLE
grammar for SQlite

### ISSUE THREAD

**Issue by elenaaralla** [coldbox-modules/qb#219]
Hello,

I'm trying to configure migration for SQLite on CommandBox using cfmigrations
But I have this error:

```
Error when trying to reset the database:
    SELECT 1 FROM "information_schema"."tables" WHERE "table_name" = 'cfmigrations' AND "table_schema" = 'sqlite_master'
ERROR (5.4.2+00453)
[SQLITE_ERROR] SQL error or missing database (no such table: information_schema.tables)
```

this are my configuration in .env file

```
# Database Information
DB_CLASS=org.sqlite.JDBC
DB_DRIVER=org.sqlite.JDBC
DB_BUNDLEVERSION=3.36.0.3
DB_CONNECTIONSTRING=jdbc:sqlite:/Users/elena/ColdBox/baseApp/database/baseAppDB.sqlite
DB_SCHEMA=sqlite_master
DB_DATABASE=baseAppDB
```

Is there a problem with default grammar?

Exists the grammar for SQLite?

Thank you,
Elena.

**Comment by elpete** [comment]
Hi, there! There isn't an official grammar for SQLite. This is something either you could write yourself or sponsor us to add. 

To add it yourself, create a new `SQLiteGrammar.cfc` that extends `BaseGrammar.cfc` and overwrite the methods needed to make it work in SQLite. There is also an `AbstractQueryBuilderSpec.cfc` and an `AbstractSchemaBuilderSpec.cfc` that you can extend to define the correct SQLite syntax so we have test coverage. 

👍🏻
