### ISSUE TITLE
Pagination throws error if returnFormat="query"

### ISSUE THREAD

**Issue by JamoCA** [coldbox-modules/qb#222]
I keep getting the following error and I don't think it's because of what I'm doing as I haven't been able to get `paginate()` to work at all regardless of the query that I use.

```
The RESULTS argument passed to the generateWithResults function is not of type array.
If the component name is specified as a type of this argument, it is possible that either a definition file for the component cannot be found or is not accessible.
 
The error occurred in C:/CFusion/cfusion/CustomTags/cbpaginator/models/Pagination.cfc: line 43
Called from C:/CFusion/cfusion/CustomTags/qb/models/Query/QueryBuilder.cfc: line 2315
```

Here's how I'm using it without CommandBox or ColdBox using ColdFusion 2016 w/MSSQL.  "qb" & "cbpaginator" libraries are both installed in the Custom Tags directory.  I also checked and downloaded the latest libraries as of 6/30/2022.
```
queryGrammar = new qb.models.Grammars.SqlServerGrammar();
queryUtils = new qb.models.Query.QueryUtils(strictDateDetection=false, numericSQLType="CF_SQL_NUMERIC");
queryBuilder = new qb.models.Query.QueryBuilder(grammar=queryGrammar, utils=queryUtils, preventDuplicateJoins=false, returnFormat="query", defaultOptions={datasource="myDatabase"});

q = queryBuilder.from("Clients");
q.paginate(1, 10);  // This throws an error. generateWithResults requires that "results" is an array.
//q.limit(10);  //  replacing it with this works...
//q.forPage( 1, 15 );  // replacing it with this works...
writeDump(var=q.get());
```

**Comment by JamoCA** [comment]
Pagination for `returnFormat="query"` doesn't appear to be supported.  (Is this documented anywhere?)  If this is intentional, could a detailed error message be added to the error?  Thanks.

**Comment by JamoCA** [comment]
Also, it doesn't appear to be mentioned in the repository or documentation, but here's the link to the library required for pagination that don't use "Box" installers or frameworks:
https://github.com/quinteroj/pagination

**Comment by elpete** [comment]
Once this dependency has a bug fix update, query objects will work with pagination: https://github.com/quinteroj/pagination/pull/13

**Comment by elpete** [comment]
Updating `cbpaginator` to v2.8.1 should fix this error.  One `box update` should do the trick.

**Comment by JamoCA** [comment]
`box update`?  (I haven't ever issued that command to update any ColdFusion/CFML project.)

I manually downloaded the updated CFC from your fork so I wouldn't have to wait for an official release.  It works great.  Thanks!
