### ISSUE TITLE
Conversion failed when converting date and/or time from character string (due to strictDateDetection=false)

### ISSUE THREAD

**Issue by JamoCA** [coldbox-modules/qb#223]
I can't control what users search for, values in other tables or values returned from functions.  I came across a strange date related error.  In the query, I was returning two (2) MSSQL DATETIME columns with WHERE clauses for two VARCHAR columns and a parameterized TIMESTAMP value.

```
mydirectory = "large";
myFileName = javacast("string", "6784.8");
q = queryBuilder.from("Art").select("FileDate, DateUpdated");
q.where("Directory", "=", myDirectory);
q.where("Filename", "=", myFilename);
q.where("DateUpdated", ">=", {"value":dateAdd("h", -97, now()), "cfsqltype":"cf_sql_timestamp"});
```
and received the following error:
```
Conversion failed when converting date and/or time from character string.
The error occurred in C:/CFusion/cfusion/CustomTags/qb/models/Grammars/BaseGrammar.cfc: line 106
Called from C:/CFusion/cfusion/CustomTags/qb/models/Query/QueryBuilder.cfc: line 3385
```

After some debugging, I determined it wasn't due to a DATETIME column being returned or a DATETIME column being queried with a TIMESTAMP value, but the VARCHAR Filename value being used.  The string being searched for is "`6784.8`" and, after dumping the SQL, QB attempts to convert this to a datetime string.  (Even if explicitly cast to a string and searching a VARCHAR field, QB attempts to convert it to a date?)

Is this a bug or expected behavior?  If expected behavior and `strictDateDetection=true`, developers will need to add `{value:"6784.8", cfsqltype="CF_SQL_VARCHAR"}` to all SELECT operations that may contain a possible value that may be considered a "valid date" by ACF/Lucee?

Is best approach to always set [`strictDateDetection` to `true`](https://qb.ortusbooks.com/query-builder/building-queries/parameters-and-bindings#strict-date-detection).  If so, I welcome this future change as it's something that broke everything and wasn't easily identified until running into it by accident and writing some unit tests.

**Comment by elpete** [comment]
You are correct that `strictDateDetection = true` will avoid this problem.  That is because in that mode it does not try to parse any dates.  We anticipate moving to that as the default in a future release.

Under `strictDateDetection = false` you only have to specify a `cfsqltype` for bindings, usually `where` statements, not in SELECT operations.

**Comment by JamoCA** [comment]
Thanks for the confirmation.  I posted it here because the error message wasn't entirely clear what the problem is and I'm hoping that it will be beneficial to have this issue returned in search engines to help others.
