### ISSUE TITLE
Setting MSSQL Isolation Level

### ISSUE THREAD

**Issue by JamoCA** [coldbox-modules/qb#227]
What's the best approach to setting the [isolation level](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-transaction-isolation-level-transact-sql?view=sql-server-ver16) for MSSQL?

I'd like to execute the following command prior to establishing up the rest of the query to perform a dirty read.
```
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
```

I don't believe this can be performed using existing `select`, `from`, `join`, _etc_ methods.

**Comment by elpete** [comment]
Isn't this something the [`cftransaction`](https://cfdocs.org/cftransaction) tag handles?

If not, this might be related to [locks](https://qb.ortusbooks.com/query-builder/building-queries/locks).

If neither of those work for you, I would say to use two queries.

**Comment by JamoCA** [comment]
I think `cftransaction` is the opposite. The "READ UNCOMMITTED" isolation level is not a rollback and performs the query while ignoring existing table locks.  It's like using `WITH (NOLOCK)` globally for a query without having to add it to every table involved in a join.  It's not the same as the existing locks feature... it would be a line of SQL executed prior to the `SELECT` query.  I can already do this if using built-in `CFQUERY` tag or `queryExecute` function.

I've tried adding multiple `noLock()` methods, but `WITH (NOLOCK)` is outputted only <s>once</s> after the first database table is defined.  (Is this a bug?)
```
q = queryBuilder.from("ArtGroups A").select("A.ID").noLock();
q.join("ArtGroupIDs AG", "A.ID", "AG.ArtGroupID").noLock();
qry = q.toSql();
writeDump(qry);
/* OUTPUT: (noLock used twice, but outputted only once on the first table)
	SELECT [A].[ID] FROM [ArtGroups] AS [A] WITH (NOLOCK)
	INNER JOIN [ArtGroupIDs] AS [AG] ON [A].[ID] = [AG].[ArtGroupID]
*/
```

Would I be required use `joinRaw` to manually include `WITH (NOLOCK)` on subsequent tables?

Here's more information regarding the usage of `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` versus `WITH (NOLOCK)` on Microsoft SQL Server.
https://blog.sqlauthority.com/2018/09/03/sql-server-applying-nolock-to-every-single-table-in-select-statement-set-transaction-isolation-level-read-uncommitted/

I also found a similar recommendation on StackOverflow:
https://stackoverflow.com/questions/18065369/sql-server-nolock-with-join-bulk-load

**Comment by JamoCA** [comment]
Another example would be if I wanted to use `SET NOCOUNT ON` for an operation. ([Microsoft SET NOCOUNT (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-nocount-transact-sql?view=sql-server-2017))

Using QB, how could I set that "ON" and the beginning of a query and then set it off at the end?  Is there a chainable pattern that would enable it to be used?

NOTE: I haven't experimented enough with native `cfquery` and `queryexecute` functions to determine if this MSSQL-only flag impacts the data returned from the JDBC driver to ColdFusion, but I have used this option when performing an UPDATE were "counts" aren't necessary.

**Comment by elpete** [comment]
I think I would be executing multiple queries for this:

**Comment by elpete** [comment]
I think I would choose to execute multiple queries for this:
```
queryExecute( "SET NOCOUNT ON" );
qb.table( "users" ).update( {} );
queryExecute( "SET NOCOUNT OFF" );
```
_Usually_ qb does not do multiple queries for you at once.  (`SchemaBuilder` is the usually exception to this rule.). If this is a cross-engine (like SQL92) way of doing things, I'd be open to building in some wrappers to qb since we control the query executing lifecycle.  But if it's just SQL Server, I'd probably recommend to stick to something like the above.
