### ISSUE TITLE
Performance issue with SQL Server and QueryUtils.inferSqlType()

### ISSUE THREAD

**Issue by dswitzer** [coldbox-modules/qb#230]
We're seeing pretty significant performance issues due to the way that `QueryUtils.inferSqlType()` works. 

The root problem when an integer value is detected, the `QueryUtils.inferSqlType()` ends up using the `CF_SQL_NUMERIC` datatype. The JDBC driver then defines those parameters as `float` in query that SQL Server executes. This leads to implicit casting of floats to integers, which has a significant impact in performance when querying tables with millions of rows.

Our execution times jump up to minutes in some cases, instead of milliseconds.

While we could set the `numericSQLType` to `CF_SQL_INTEGER` on the `QueryUtils` instance, we have the same basic problem with numeric values that are not integers.

What I'd propose is that a new `integerSQLType` option is introduced. This the SQL datatype to use for values that are detected as integers. 

If backwards compatibility is an issue, you could default this to `CF_SQL_NUMERIC` so the behavior is the same, but I'd recommend this defaults to `CF_SQL_INTEGER`.

Then in the `inferSqlType()` function before the `checkIsActuallyNumeric()`, you'd check to see if the value is actually an integer (has no decimal, e.g. would pass a regex check of `^\d+$`) and if so then it uses the `integerSQLType` datatype.

This would allow different datatypes for integers and decimal values.

I've taken this approach with our codebase, by creating a new QueryUtils component that extends the base component and adds this check. This has fixed a lot of performance issues we've been seeing.

It took us a while to figure out what's going on since all this is abstracted from the code we're writing. It wasn't until I started looking at the cache execution plans that I noticed the behavior.

**Comment by elpete** [comment]
Hi, Dan. Thanks for the issue.

I'm a little hesitant to introduce regex checks since I don't want to slow down the code if I can help it.

I already have this snippet in the code:

```cfc
/**
 * Detects if value is numeric based on className
 *
 * @value The value
 *
 * @return boolean
 */
private boolean function checkIsActuallyNumeric( any value ) {
    if ( isNull( arguments.value ) ) {
        return false;
    }
    return isSimpleValue( arguments.value ) && arrayContainsNoCase(
        [
            "CFDouble",
            "Integer",
            "Double",
            "Float",
            "Long",
            "Short"
        ],
        listLast( getMetadata( arguments.value ), ". " )
    );
}
```

It seems we could piggy back on this and return the correct data type for each of those number types.  How do you think that would affect your performance testing?

Something like this:
```cfc
/**
 * Detects if value is numeric based on className
 *
 * @value The value
 *
 * @return boolean
 */
private boolean function deriveNumericSqlType( any value ) {
    if ( isNull( arguments.value ) ) {
        return "";
    }

    if ( !isSimpleValue( arguments.value ) ) {
        return "";
    }

    var numberType = listLast( getMetadata( arguments.value ), ". " );
    switch ( numberType ) {
        "CFDouble":
        "Double":
            return "CF_SQL_DOUBLE";
        "Float":
            return "CF_SQL_FLOAT";
        "Integer":
        "Long":
        "Short":
            return "CF_SQL_INTEGER";
        default:
            return "";
    }
}
```

It's still not perfect as the `LONG` may better map to `BIGINT`,  but then again that depends on how the database was set up.  As always, an explicit query param struct [will always take precedence and skip the inferring.](https://qb.ortusbooks.com/query-builder/building-queries/parameters-and-bindings#custom-parameter-types)

Thoughts?

**Comment by elpete** [comment]
One other mention, this does not help in older ACF codebases where Adobe would store all numbers as a string.  Additionally, if the engines store all numbers as `Double`, for instance, this also would not help.  Some more testing is warranted.

**Comment by elpete** [comment]
> One other mention, this does not help in older ACF codebases where Adobe would store all numbers as a string. Additionally, if the engines store all numbers as `Double`, for instance, this also would not help. Some more testing is warranted.

So, yeah, Lucee stores it all as doubles.  So this trick won't work.  I'll need to benchmark how long the regex takes.  I don't want to introduce a performance problem while trying to fix another one.

**Comment by dswitzer** [comment]
@elpete,

This is what we're currently using:

```
    /**
     * Detects if value is an integer based on className
     *
     * @value The value
     *
     * @return boolean
     */
    private boolean function checkIsActuallyInteger( any value ) {
        if ( isNull( arguments.value ) ) {
            return false;
        }

        return isSimpleValue( arguments.value ) && reFind("^\d+$", arguments.value) && !arrayContainsNoCase(["Float", "DateTimeImpl"], listLast(getMetadata(arguments.value), "."));
    }
```

As you already figured out, Lucee stores the numbers as `Double` (which is the engine we're using). I have the `Float` check in there so that for values specifically cast to a float, it'll keep using the `numeric` logic.

The regex is pretty performant. Here's a sample GIST:

https://www.trycf.com/gist/92d36780fcca8e7c45ee4d822d100de3/lucee5?theme=monokai

An iteration over 10,000 loops runs in a few milliseconds. The regex is actually faster than the getMetadata() code.

**Comment by dswitzer** [comment]
Thanks for implementing this.

Just as an update, since going live with our custom patch send integers as proper ints, we have seen a dramatic speed increase. Our average JDBC query times have dropped 50% based on our FusionReactor logs. So I believe this will pay major dividends for anyone using SQL Server.
