### ISSUE TITLE
InsertUsing does not like CTEs

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#234]
In SQL Server, if you try to insert the result of a CTE rather than a normal select, the "WITH" clause ends up in the wrong location, breaking the query.  According to this, rearranging the query is all that is necessary.

https://stackoverflow.com/questions/3306096/combining-insert-into-and-with-cte

It appears that in MySQL, the existing syntax would work if the semicolon is removed.  https://stackoverflow.com/questions/72255787/insert-into-table-from-cte

**Comment by elpete** [comment]
Could you provide a qb example and the corresponding SQL it should generate?
