### ISSUE TITLE
Please add convenience method addSelectRaw()

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#249]
For consistency with reselectRaw.  This works in a pinch.

```
.when( bFirstRun, ( q ) => {
  q.addSelect( qb.raw( "case when row_rank = 1 then 1 else 0 end as bSelected" ) )
} )
                ```

**Comment by elpete** [comment]
`selectRaw` already appends to the columns.

**Comment by Daemach** [comment]
Good to know, but it's not obvious, at least to me.  An alias would be nice
and 0 overhead.
