### ISSUE TITLE
PostgresGrammar schema issue with table_catalog

### ISSUE THREAD

**Issue by mjclemente** [coldbox-modules/qb#250]
On lines [376](https://github.com/coldbox-modules/qb/blob/eb76dc3bb2b42bcdbcf0a4a6ed4b2c0cb82f1f0c/models/Grammars/PostgresGrammar.cfc#L376) and [390](https://github.com/coldbox-modules/qb/blob/eb76dc3bb2b42bcdbcf0a4a6ed4b2c0cb82f1f0c/models/Grammars/PostgresGrammar.cfc#LL390C47-L390C47), the PostgresGrammar.cfc references `table_catalog` when checking the schema.

At least in my current Postgres install (v14), `table_catalog` refers to the database name, while `table_schema` refers to the schema: 
<img width="702" alt="image" src="https://github.com/coldbox-modules/qb/assets/5348419/446d6f39-3d27-44b1-8b34-0114238e92fa">

Consequently, I am unable to use cfmigrations/commandbox-migrations - they keep being unable to determine if the `cfmigrations` table is installed.

(as a side note, their versions of qb are a bit behind).

Happy to provide more info as needed.

Thanks!

**Comment by elpete** [comment]
Fixed in v9.1.5
