### ISSUE TITLE
[Improvement] Add a Limit() Method to Only Return X Number of Results

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/qb#276]
It would be helpful to be able to limit the number of results in queries.  Currently it's easy to get the `first()` record, `paginate()`, and `get()` all records.

I could see `limit()` working like this:
```
// get the first 5 rows from the product table
qb.get( "product" ).limit( 5 ).get();
```

**Comment by elpete** [comment]
https://qb.ortusbooks.com/query-builder/building-queries/limit-offset-and-pagination

**Comment by homestar9** [comment]
Brainfart! Sorry Eric!
