### ISSUE TITLE
OrtusBooks QB "Installation & Usage" doesn't mention manual installation

### ISSUE THREAD

**Issue by JamoCA** [coldbox-modules/qb#286]
I use QB with my non-Box CFML apps, but I didn't have to install it using CommandBox and ForgeBox.  (I wanted to recommend this to another developer, but I didn't want them to get frustrated because they had to learn something else before they could start using QB.)

Please update the instructions located at https://qb.ortusbooks.com/installation-and-usage to include manual installation instructions and generic non-ColdBox usage.

Thanks.

**Comment by elpete** [comment]
Good news! The qb docs are open source.  You can submit a PR here: https://github.com/ortus-docs/qb-docs/pulls
