### ISSUE TITLE
Should the execution methods reset the builder?

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/qb#30]
Currently when calling an execution method (think `get`, `insert`, `count`, `delete`, etc), the sql fragments remain intact.  Here's an example:

```
// 1st query
query.from( "users" ).delete( 5 );
// sql: DELETE FROM users WHERE id = ?
// bindings: [ 5 ]

// 2nd query, same builder (query) object
query.from( "users" ).get();
// ERROR: “there are more question marks in the SQL than params defined”
// sql: SELECT * FROM users WHERE id = ?
// bindings: []
```

I _believe_ this is a bug and the builder should be reset each time an execution is ran.

The **question** is is there any situation where you would want the builder to remember the fragments?  Please sound off below.

**Comment by Adrian-Sanchez** [comment]
Although it was a gotcha for me....I'm leaning towards liking this functionality. However, i think it would helpful to others to have supporting documentation to know what to expect. It also presents some challenges in terms of what is expected if the "bug" becomes intended. 

**Updated after all that's below:** Oh geez, i started off just trying to type a simple response but this is what i ended up with...more questions

## keeping fragments 
### a delete
`query.from( "users" ).delete( 5 );`
`var result = query.from( "users" ).get(); `
result: [ ]
**Result: should it return all users or become a test that the id =5 no longer exists?**

`query.from( "users" ).count( );`
count: 0
**Result: Should it count all users or become a test that the id =5 no longer exists?**

### an insert
`query.from( "users" ).insert( values = { "name" = "Robert", "email" = "robert@test.com", "age" = 55 } )`
`var result = query.from( "users" ).get(); //inserted values but does it return other row values?`

result: [ { "name" = "Robert", "email" = "robert@test.com", "age" = 55 ...other cols} ]
**Result: from a sql query but should it return other row columns?**

`query.from( "users" ).count( );`
count: 1

### a mutiple insert
`query.from( "users" )`
`.insert( values = [`
 `       { "name" = "Robert", "email" = "robert@test.com", "age" = 55 },`
 `       { "name" = "Jessica", "email" = "jessica@test.com", "age" = 31 },`
  `      { "name" = "Ross", "email" = "ross@test.com", "age" = 9 }`
  `  ] );`
`var result = query.from( "users" ).get();`

result: [
        { "name" = "Robert", "email" = "robert@test.com", "age" = 55 ...other cols},
        { "name" = "Jessica", "email" = "jessica@test.com", "age" = 31 ...other cols},
        { "name" = "Ross", "email" = "ross@test.com", "age" = 9 ...other cols}
    ] 
 **Result: Inserted values but again, should it return other row columns?**
`query.from( "users" ).count( );`'
count:3

### In general
**Should fragments remain after inserts, updates?**
**Or should fragments remain based on certain conditions like after a get() with where criteria or something else?**

## My two cents:

> Pros:
> - Provide some programmatic shortcuts. 

> Cons:
> - Results expected can be subjective.
> - The use of the newQuery() function in a preexecute or a postExecute of removing fragments could possible eliminate all this ambiguity

> In any case:
> - Some updated docs on expected behavior.
> - In particular the use of the newQuery() function to reset the fragments on demand
> - Feeling sorry for Eric, i'm sure he has better, more financially incentivized things to do.

**Comment by wpdebruin** [comment]
I think the builder should be reset after execution methods.  Otherwise it is confusing what to expect as a result.
I am perfectly fine using newQuery(), but  it is important this method can be found in the documentation.

**Comment by wpdebruin** [comment]
Ok, never mind, I see the newQuery stuff just has been added to the docs :-)

**Comment by elpete** [comment]
I’m going to close this issue and choose not to reset the builder. I don’t want to encourage reusing the same query builder object over again.
