### ISSUE TITLE
Dynamic JOIN statements (pad, trim, etc.)

### ISSUE THREAD

**Issue by murphydan** [coldbox-modules/qb#4]
It is sometimes needed to do a join like so (Oracle specific syntax, maybe)...

```
SELECT 
    t1.bleh,
    t2.blah
FROM table1 t1
JOIN table2 t2
    ON t1.thing = LPAD(t2.thing,10,'0')
```

**Comment by elpete** [comment]
Use `query.raw( "LPAD(t2.thing,10,'0')" )`.

`raw` is exactly what it sounds like — exactly what you type in.

**Comment by elpete** [comment]
So `.join( "t1.thing", "=", query.raw( "LPAD(t2.thing,10,'0')" ) )`
