### ISSUE TITLE
Using database function calls in QB

### ISSUE THREAD

**Issue by dswitzer** [coldbox-modules/qb#43]
I've been poking around in the source code and reading the documentation, but I'm not seeing how one might use native and user-defined functions.

For example:

How would I write:

```
select
  id, Name, coalesce(MobilePhone, HomePhone) as ContactNumber
from
  Customer
```

The parse chokes with the `coalesce()` function.

Likewise, how would I do something like:

```
select
  id, Name, dbo.ContactNumber(id) as ContactNumber
from
  Customer
```

Lastly, it doesn't seem to be able to define a query that uses a table that comes from a UDF. For example:

```
select
  dateInterval.start_date as Hour, count(o.id) as TotalOrders
from
  dbo.generateDates('h', '2018-07-26 00:00:00', '2018-07-26 23:59:59.997') as dateInterval
     left join
  Orders as o
    o.OrderDate between dateInterval.start_date and dateInterval.end_date
group by
  dateInterval.start_date
order by
  dateInterval.start_date
```

Is there any way to accomplish these kinds of queries today?

**Comment by dswitzer** [comment]
Ok, I figured out how to handle the column issue, you can use the `raw()` method:

```
 qb.from('Customer')
	.select("id", "Name", qb.raw("coalesce(MobilePhone, HomePhone) as ContactNumber"))
	.get()
```

and

```
 qb.from('Customer')
	.select("id", "Name", qb.raw("dbo.ContactNumber(id) as ContactNumber"))
	.get()
```

However, the `raw()` returns an object not usable by the `from()` or `join()` methods.

**Comment by elpete** [comment]
Fixed in https://github.com/coldbox-modules/qb/releases/tag/v5.7.0
