### ISSUE TITLE
MSSQL: Replace current implementation of `text`

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/qb#54]
MSSQL is [deprecating and removing the NTEXT and TEXT types](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-2017).  Luckily, for those using qb, this should be as easy as upgrading to the next version.

The functions `text` (and `unicodeText` when it is added) should remain unchanged.  The change will be in the `MSSQLGrammar` file and the `typeText` (`typeUnicodeText`) functions.  They should instead use `VARCHAR(MAX)` (`NVARCHAR(MAX)`).

This change can be made at any time since the underlying functionality should be the same.

**Comment by wpdebruin** [comment]
One assumption: you should be at least using mssql 2005 which was eol on April 12 2016. So if we agree we don't need support for prehistoric stuff, the change is easy, at least for TEXT.

**Comment by elpete** [comment]
Validate this assumption for me — even if your are using MSSQL < 2005 this change will still be supported, right?  Said another way, `VARCHAR(MAX)` is supported on old versions of MSSQL as well, correct?

**Comment by elpete** [comment]
Moved to https://ortussolutions.atlassian.net/projects/QB/issues/QB-11
