### ISSUE TITLE
QB doesn't support uppercase LIKE operator

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/qb#69]
1. Could we update `isInvalidOperator()` to use `arrayContainsNoCase()` to support all case variants of `like`? See https://github.com/coldbox-modules/qb/blob/22212761b3b262bade655e08a8fb9e83ef15ee43/models/Query/QueryBuilder.cfc#L2664

2. Technically I would stress using `arrayFind()` over `arrayContains()`  - the former will only return true for an *exact* match, whereas `arrayContains(["like"],"i")` will return true if it finds an `i` in any of the array items - not an exact match. I suppose that allows spaces around equal signs for developers though, like `q.where("name"," = ", "Michael");`. Still not a fan. :)

**Comment by elpete** [comment]
[`arrayContainsNoCase`](https://cfdocs.org/arraycontainsnocase) is not supported on ACF 11, which is still a supported engine for qb.  This could definitely be modified to compare the `lcase`'d versions or the like.  I look forward to your PR. 👍

Also, I don't think you are correct about `arrayContains` and substrings.  Try running this code in TryCF and see what you get. (I get `false`.)
```
writeDump(arrayContains(["like"],"i"))
```

**Comment by michaelborn** [comment]
Hotdog - I guess it's only `listContains()` that behaves like that, I'm sorry. I'm not impressed with the inconsistent behavior of `listContains()` and `arrayContains()`, then, but that's a totally different conversation.

Writing up a fix now, running tests. :)

**Comment by elpete** [comment]
Thanks for the fix, @michaelborn
